// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYvUsQc9T4-IVIVyDk1oSa00Bb3I49jhI',
    appId: '1:734611718185:web:a192dc26ce6b9bef87dc38',
    messagingSenderId: '734611718185',
    projectId: 'softphone-ff414',
    authDomain: 'softphone-ff414.firebaseapp.com',
    storageBucket: 'softphone-ff414.firebasestorage.app',
    measurementId: 'G-1DQJT6J5B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOa1GhKfoNLwjJbg9NelSFJQmGWeGQow',
    appId: '1:734611718185:android:94cb66cd6d1bda0887dc38',
    messagingSenderId: '734611718185',
    projectId: 'softphone-ff414',
    storageBucket: 'softphone-ff414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfwPPoo13WLtvIi0SXXsxe0KndNlf2sY',
    appId: '1:734611718185:ios:9beea74807d51cbc87dc38',
    messagingSenderId: '734611718185',
    projectId: 'softphone-ff414',
    storageBucket: 'softphone-ff414.firebasestorage.app',
    iosBundleId: 'com.example.softphoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvfwPPoo13WLtvIi0SXXsxe0KndNlf2sY',
    appId: '1:734611718185:ios:9beea74807d51cbc87dc38',
    messagingSenderId: '734611718185',
    projectId: 'softphone-ff414',
    storageBucket: 'softphone-ff414.firebasestorage.app',
    iosBundleId: 'com.example.softphoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYvUsQc9T4-IVIVyDk1oSa00Bb3I49jhI',
    appId: '1:734611718185:web:6ef2fc218193fc0087dc38',
    messagingSenderId: '734611718185',
    projectId: 'softphone-ff414',
    authDomain: 'softphone-ff414.firebaseapp.com',
    storageBucket: 'softphone-ff414.firebasestorage.app',
    measurementId: 'G-JMFQP46FSV',
  );
}
